[telegram]

bot_token = "1733931112:AAGdRjwf10J9L2-Pg6SZ4o2eLq_nQu7Dze0"

[fyers]
user_id = "DA00190"
client_id = "HJ2321XETS-100"
secret_key = "E5YVX47DYK"
redirect_uri = "https://127.0.0.1"
totp_token = "2AGVWA4LCIUWVDQ433KPJ35N44ADR2ZX"
pin = "1234"

[mongo_db]
mongo_url = "mongodb://akshay:Learnapp1234@cluster0-shard-00-00.9hpry.mongodb.net:27017,cluster0-shard-00-01.9hpry.mongodb.net:27017,cluster0-shard-00-02.9hpry.mongodb.net:27017/myFirstDatabase?ssl=true&replicaSet=atlas-9goxcz-shard-0&authSource=admin&retryWrites=true&w=majority"
